### PR TITLE
DISPATCH-2120 Create GitHub Actions jobs used for gating incoming pull requests

### PR DESCRIPTION
**Pull request by jiridanek**
I decided to use Fedora in Docker instead of Ubuntu, to make the steps more similar to the CentOS; also, not splitting the builds into compile job and test job simplifies things, at the cost of having to compile everything twice (for every one of the two shards).

### CODE REVIEW

**Comment by jiridanek** [comment]
I've disabled ord check and reported https://issues.apache.org/jira/browse/DISPATCH-2148 PN_WEAKREF odr-violation in test-sender coming from Proton c/src/core/object/object.c:315

**Comment by jiridanek** [comment]
TSan issues, previously unreported, added to suppressions https://issues.apache.org/jira/browse/DISPATCH-2151, https://issues.apache.org/jira/browse/DISPATCH-2152, https://issues.apache.org/jira/browse/DISPATCH-2153

**Comment by jiridanek** [comment]
Reopened https://issues.apache.org/jira/browse/DISPATCH-2024

**Comment by jiridanek** [comment]
Saw https://issues.apache.org/jira/browse/DISPATCH-2115 hapen on all three arches at this point.

Reopened https://issues.apache.org/jira/browse/DISPATCH-1797

**Comment by jiridanek** [comment]
Two more tsan warnings, again involving Proton, https://issues.apache.org/jira/browse/DISPATCH-2155, https://issues.apache.org/jira/browse/DISPATCH-2156. Both now suppressed.

**Review by kgiusti — APPROVED** [review]
It looks like the build/test is doing what we want.   Once all the new tsan issues are JIRA'ed and suppressed feel free to submit this patch.

**Pull request merged**
