### PR TITLE
DISPATCH-938: Remove config ref and add links to qdrouterd.conf man page

### PR DESCRIPTION
**Pull request by bhardesty**

### CODE REVIEW

**Comment by bhardesty** [comment]
@enkeys @fgiorgetti  

This PR is ready for doc testing. The changes are simple, so it should be a good candidate to start with.

**Comment by fgiorgetti** [comment]
Thanks @bhardesty. We will start with this one.

**Comment by fgiorgetti** [comment]
Can you mark us as reviewers here?

**Comment by bhardesty** [comment]
@fgiorgetti I don't have write access, so I can't assign reviewers.

**Pull request closed without merging**
