### PR TITLE
DISPATCH-1933 Tests should produce JUnit-compatible XML report about individual tests (not aggregated CTest test targets)

### PR DESCRIPTION
**Pull request by jiridanek**
This PR gives the user control over the command used to run Dispatch System tests written with Python unittest. There are many Python test runners that can run these tests, and some have advanced features.

For example, Pytest can (out-of-the-box) generate XML JUnit style reports. The reports surface info about e.g. individual skipped tests to some CI system like Jenkins. There is a Pytest plugin which automatically reruns failed tests, to check if it was a flaky failure or if the test is deterministically broken https://github.com/pytest-dev/pytest-rerunfailures. And so on.

### CODE REVIEW

**Comment by jiridanek** [comment]
@fgiorgetti [~fgiorget] Here's the idea for fancier XML reporting from Dispatch tests. I sent you private link to what the result looks like currently. The job definition for that is https://github.com/jiridanek/rhm-ci-jenkins/blob/jd_pytest/dispatch.sh (you should have perms to view, I hope).

**Comment by jiridanek** [comment]
Going over this again, it looks to me that all the necessary pieces are there. Just few small details missing, around it.

## TODO

* get rid of this silly warning

```
34: =============================== warnings summary ===============================
34: ../../tests/system_test.py:1310
34:   /foo/qpid-dispatch/tests/system_test.py:1310: PytestCollectionWarning: cannot collect test class 'TestTimeout' because it has a __init__ constructor (from: )
34:     class TestTimeout(object):
34: 
34: -- Docs: https://docs.pytest.org/en/stable/warnings.html
34: - generated xml file: /foo/qpid-dispatch/build/tests/junitxmls/system_tests_two_routers.xml -
34: =================== 32 passed, 1 warning in 64.90s (0:01:04) ===================
```

* figure out how best to install pytest on RHEL 7
* decide on precise pytest command we want, it should probably include `--junit-prefix=`
* use this in ASF Jenkins?
* does it still work without `tox`? (see related cmake magic)

**Comment by jiridanek** [comment]
One more issue. Tests in `management_test` are each collected twice, under both their "names":

```
11: collecting ... collected 20 items
11: 
11: __init__.py::EntityTest::test_camelcase PASSED
11: __init__.py::EntityTest::test_entity PASSED
11: __init__.py::QdrouterTest::test_qdrouter_parse_camel PASSED
11: __init__.py::QdrouterTest::test_qdrouter_parse_dash PASSED
11: __init__.py::SchemaTest::test_attribute_def PASSED
11: __init__.py::SchemaTest::test_bool PASSED
11: __init__.py::SchemaTest::test_entity_type PASSED
11: __init__.py::SchemaTest::test_enum PASSED
11: __init__.py::SchemaTest::test_schema_entity PASSED
11: __init__.py::SchemaTest::test_schema_validate PASSED
11: entity.py::EntityTest::test_camelcase PASSED
11: entity.py::EntityTest::test_entity PASSED
11: qdrouter.py::QdrouterTest::test_qdrouter_parse_camel PASSED
11: qdrouter.py::QdrouterTest::test_qdrouter_parse_dash PASSED
11: schema.py::SchemaTest::test_attribute_def PASSED
11: schema.py::SchemaTest::test_bool PASSED
11: schema.py::SchemaTest::test_entity_type PASSED
11: schema.py::SchemaTest::test_enum PASSED
11: schema.py::SchemaTest::test_schema_entity PASSED
11: schema.py::SchemaTest::test_schema_validate PASSED
```

**Comment by fgiorgetti** [comment]
@jiridanek it seems to be working just fine. Great contribution as usual. Thank you very much.

**Comment by jiridanek** [comment]
I am strongly tempted to leave the pytest in for the GitHub Action run. That way there will be feedback that it actually works that way. I could maybe add a html results report.... I have to see how to merge results from multiple runs of Pytest.

**Comment by jiridanek** [comment]
image

**Pull request merged**
