### PR TITLE
NO-JIRA Consistently use Python 3 in all Travis CI jobs (#1449)

### PR DESCRIPTION
**Pull request by kgiusti**
(cherry picked from commit b20d679b882ad8781a7ec32c8ea3c77a1b3ea62c)

### CODE REVIEW

**Review by jiridanek — COMMENTED** [review]
If Travis passes green, then merge!

Otherwise, feel free to see me about it, feel free to scream.

**Comment by kgiusti** [comment]
> If Travis passes green, then merge!
> 
> Otherwise, feel free to see me about it, feel free to scream.

No screaming, but it appeared to fail travis due to the patch:
https://app.travis-ci.com/github/apache/qpid-dispatch/jobs/550638539#L720

Should this patch not include the change in the clang version? @jiridanek

**Comment by jiridanek** [comment]
> > If Travis passes green, then merge!
> > Otherwise, feel free to see me about it, feel free to scream.
> 
> No screaming, but it appeared to fail travis due to the patch: https://app.travis-ci.com/github/apache/qpid-dispatch/jobs/550638539#L720
> 
> Should this patch not include the change in the clang version? @jiridanek

That's one way of fixing it, I guess. The other would be to also cherry-pick https://github.com/apache/qpid-dispatch/commit/f5894a16fc02a4a32aa6ebac7d66c2c7d054c307. Essentially, make the .travis.yml be what it is on main branch.

**Comment by jiridanek** [comment]
GHA fail is known issue also present on main, https://issues.apache.org/jira/browse/DISPATCH-2206

**Pull request closed without merging**
