### PR TITLE
DISPATCH-2355: Implement the `format` attribute for `qd_log_impl` and…

### PR DESCRIPTION
**Pull request by jiridanek**
… other such functions to hopefully have compile-time check for format strings

This is backported code from skupper-router, https://github.com/skupperproject/skupper-router/issues/1011

### CODE REVIEW

**Comment by jiridanek** [comment]
This is going to need the .whl locating machinery from https://github.com/skupperproject/skupper-router/pull/911/files or maybe https://github.com/skupperproject/skupper-router/pull/928

**Comment by jiridanek** [comment]
@dependabot rebase

**Comment by jiridanek** [comment]
@ganeshmurthy 100% tests pass again!

**Review by ganeshmurthy — APPROVED** [review]

**Comment by ganeshmurthy** [comment]
> 100% tests pass again!

When it rains, it pours !!

**Pull request merged**
